image:
  repository: priyankasingh06/hello-world
  tag: v1
service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  automount: true
  annotations: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: hello-world.local
      paths:
        - path: /
          pathType: Prefix
